spring:
  datasource:
    druid:
      operator:
        url: jdbc:mysql://1localhost/operator?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: xxxx
        password: xxxx
        driverClassName: com.mysql.jdbc.Driver
        initial-size: 2
        max-active: 2
        min-idle: 2
        test-on-borrow: true
        validation-query: select 1
        connection-init-sqls: SET NAMES utf8mb4
      message:
        url: jdbc:mysql://localhost:3306/message?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: xxxx
        password: xxxx
        driverClassName: com.mysql.jdbc.Driver
        initial-size: 2
        max-active: 2
        min-idle: 2
        test-on-borrow: true
        validation-query: select 1
        connection-init-sqls: SET NAMES utf8mb4
  jpa:
    show-sql: true
