server:
  port: 8082
  servlet:
    context-path: /demo-nacos-provider
spring:
  application:
    name: demo-nacos-provider
dubbo:
  protocol:
    name: dubbo
    port: -1
  application:
    name: ${spring.application.name}
    logger: slf4j
    qosEnable: false
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
demo:
  service:
    version: 1.0.0
    name: tmyService


