server:
  servlet:
    context-path: /demo-mongo
  port: 8085

spring:
  mongodb:
    host: 10.18.56.240
    port: 10000
    database: timeline
    username: timeline_rw
    password: V23mZVbjc86tJ22