server:
  servlet:
    context-path: /demo-redis
  port: 8082

spring:
  redis:
    host: 10.19.10.52     # Redis服务器地址
    port: 1183          # Redis服务器端口
    password: d779003dffb1454690ea805c3efc0b12          # 密码，如果没有则留空
    database: 0         # 数据库索引 (0-15)
    timeout: 2000ms     # 连接超时时间
    ssl: false          # 是否启用SSL
    # Jedis 连接池配置
    jedis:
      pool:
        enabled: true   # 启用连接池
        max-active: 20  # 最大连接数
        max-idle: 10    # 最大空闲连接数
        min-idle: 2     # 最小空闲连接数
        max-wait: 1000ms # 获取连接时的最大等待时间
        time-between-eviction-runs: 30000ms # 空闲连接检查周期
#    redisson:
#      file: classpath:redisson-config-${spring.profiles.active}.yaml


