server:
  servlet:
    context-path: /demo-redis
  port: 8082

spring:
  redis:
    host: 10.16.76.146
    port: 6379
    password: Sohu@123456
    max-wait: -1ms
    max-idle: 8
    max-active: 8
    min-idle: 1
    shutdown-timeout: 100ms
    redisson:
      file: classpath:redisson-config-${spring.profiles.active}.yaml


