server:
  port: 8080
  servlet:
    context-path: /demo-nacos-config
spring:
  application:
    name: demo-nacos-config
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 172.0.0.1:8848
    username: nacos
    password: nacos
    namespace: three-demo-test
    group: test_group
    data-ids: test_data.yml
    type: yaml
    auto-refresh: true
  discovery:
    server-addr: 172.0.0.1:8848
